spring:
  application:
    name: Kkri

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100
  servlet:
    multipart:
      enabled: true
      location: C:\tempImage/
      max-file-size: 10MB
      max-request-size: 100MB
      file-size-threshold: 1MB




logging.level:
    org.hibernate.SQL: debug
